### ISSUE TITLE
[Sling-framework] Upgrade Lerna to its last version

### ISSUE THREAD

**Issue by biancarosa** [stone-payments/sling-web-framework#4]
### Issue Description
There is a new version of Lerna that we could be using.

### Expected Behaviour
Lerna should be upgraded to the latest version.

### Checklist
- [ ] Deployment scripts are not broken

**Comment by ayr-ton** [comment]
Working on this one

**Comment by ayr-ton** [comment]
Do you prefer fixed versions instead versions with `^`?
I ran the tests and nothing is failing, which workflow I could run to validate if the deployment scripts are not broken? Thank you for your time reviewing.

**Comment by ayr-ton** [comment]
Is the `semantic-release` working as expected? 😄
