### ISSUE TITLE
[Sling-framework] Use just .travis.yml to get rid of unnecessary logic on sh scripts

### ISSUE THREAD

**Issue by biancarosa** [stone-payments/sling-web-framework#7]
### Issue Description
Currently, the before_install and the after_success scripts are being used, but according to [this](https://docs.travis-ci.com/user/deployment/npm/) guide, it shouldn't be necessary.

### Expected Behaviour
The whole release process should be simpler and just use the .travis.yml file.

**Comment by ayr-ton** [comment]
Trying to implement this one before midnight

**Comment by ayr-ton** [comment]
@biancarosa How could we deal with the following options inside the `deploy` from travis?
```
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
```
After decide I could amend the commit with the solution.

**Comment by joselitojunior1** [comment]
@ayr-ton maybe is possible using environment variables?

**Comment by ayr-ton** [comment]
@joselitojunior1 Could I do that without access to the stone-payments travis-ci account?

**Comment by leofavre** [comment]
@ayr-ton @biancarosa

Actually, we should start using [semantic-release](https://github.com/semantic-release/semantic-release) and [semantic-release-monorepo](https://github.com/Updater/semantic-release-monorepo). 

I have the configuration set on https://github.com/leofavre/memory-game-elements (.travis.yml, .releaserc.json, lerna.json and package.json). It's just a matter of installing the correct npm packages and copying the configuration.

This will also require us to set NPM_TOKEN and GH_TOKEN variables on Travis CI, so `email` and `api_key` won't have to be set.

**Comment by ayr-ton** [comment]
@leofavre Thanks. I will try to implement this based on your code sample. 💃

**Comment by joselitojunior1** [comment]
@ayr-ton Tell us if you need any help.

**Comment by ayr-ton** [comment]
@joselitojunior1 @leofavre @biancarosa ready for review, let me know if the new PR works and about improvement opportunities o/
