### ISSUE TITLE
[Sling-card] Fix Card Basic component

### ISSUE THREAD

**Issue by caiomdias** [stone-payments/sling-web-framework#71]
**I'm submitting a:**

[ ] bug report
[x] feature request
[ ] support request

**Current behavior:**

The Card should be able to hide the slots that do not have content. Right now, the logic that was meant to do it is failing.

![screen shot 2018-05-31 at 17 14 01](https://user-images.githubusercontent.com/125764/40805884-1d67d48e-64f6-11e8-81b0-a9dbaabaacef.png)

**Expected behavior:**

The card should not have white space when Header, Body or Footer slots are not used.

They should look like this:

![screen shot 2018-05-31 at 17 14 23](https://user-images.githubusercontent.com/125764/40805894-24415014-64f6-11e8-91df-24dc106d5149.png)

**Comment by joselitojunior1** [comment]
Fixed #83
